---
banknotes:
  500: 2
  200: 2
  100: 2
  50: 2
  20: 2
  10: 2
  5: 2
  2: 2
  1: 2
accounts:
  3321:
    name: Volodymyr
    password: mypass
    balance: 973
  5922:
    name: Iryna
    password: ho#ll_ยง1
    balance: 5301
