---
banknotes:
  500: 2
  200: 0
  100: 0
  50: 0
  20: 2
  10: 2
  5: 2
  2: 0
  1: 0
accounts:
  3321:
    name: Volodymyr
    password: mypass
    balance: 267
  5922:
    name: Iryna
    password: ho#ll_ยง1
    balance: 5301
