---
banknotes:
  500: 2
  200: 1
  100: 0
  50: 1
  20: 1
  10: 2
  5: 1
  2: 1
  1: 0
accounts:
  3321:
    name: Volodymyr
    password: mypass
    balance: 1383
  5922:
    name: Iryna
    password: ho#ll_ยง1
    balance: 5301
